### ISSUE TITLE
Unit Testing Following the Examples....

### ISSUE THREAD

**Issue by DasNaughtie** [MassTransit/Sample-Library#2]
Hi There,

Hope all is well.

I've copied the example consumer unit test using the MassTransit TestHarness and I cannot get it to work...it always timesout.  I've read the website documentation more times then I would like to admit and I still can't see a solution.  I've followed countless examples and they all end the same way.

Are you able to explain why I'm seeing this error?  I've followed the documentation so I really don't understand why it's not working.  Works fine when I run the code but the unit test is always returning a time out.  

So frustrating!

**Comment by phatboyg** [comment]
Without a complete example reproducing the issues, it's impossible to troubleshoot. An issue on the sample isn't the right approach.

**Comment by DasNaughtie** [comment]
Thanks for the update…will post the code to a new issue when I get home
tonight.
